"""ReviewShares Table

Revision ID: 305e7a5ceb01
Revises: 1afb4f2625e5
Create Date: 2025-05-15 21:33:11.952274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305e7a5ceb01'
down_revision = '1afb4f2625e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_shares',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='required'),
    sa.PrimaryKeyConstraint('share_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_shares')
    # ### end Alembic commands ###
