"""Added Table ReviewShares

Revision ID: e554cfb6e66a
Revises: bad7c06bfc5c
Create Date: 2025-05-07 19:40:10.143845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e554cfb6e66a'
down_revision = 'bad7c06bfc5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_shares',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('shared', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('share_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_shares')
    # ### end Alembic commands ###
