"""Username Col

Revision ID: f3c0a0e799f7
Revises: 305e7a5ceb01
Create Date: 2025-05-15 21:34:04.268843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c0a0e799f7'
down_revision = '305e7a5ceb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key('required2', 'user', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_shares', schema=None) as batch_op:
        batch_op.drop_constraint('required2', type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
